/**
 * @generated by `astryx theme build`: do not edit manually.
 * Source: src/theme/orgTheme.ts
 * Command: astryx theme build src/theme/orgTheme.ts --out src/theme/orgTheme.css
 */

/// <reference path="./org.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const orgTheme: DefinedTheme;
