/**
 * @generated by `astryx theme build`: do not edit manually.
 * Source: src/theme/orgTheme.ts
 * Command: astryx theme build src/theme/orgTheme.ts --out src/theme/orgTheme.css
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
